# Use an official Python runtime as a parent image
FROM python:3.9.7-slim

# Install system packages
RUN apt-get update && \
    apt-get install --no-install-recommends -y gcc python3-dev default-libmysqlclient-dev &&\
    apt-get clean

# Set the working directory in the container
WORKDIR /backend

# Copy the current directory contents into the container at /backend
COPY ./requirements.txt /backend/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./ /backend/

# Expose the port
EXPOSE 80

# Run the App
CMD ["python", "-u", "app.py"]