version: '3'
services:
  fast-api-test:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fast-api-con
    image: fast-api-img
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    volumes:
      - "./:/app/"
      