version: '3'
services:
  ubuntu-server:
    image: ubuntu-server
    container_name: ubuntu-server-cont
    command: ["/bin/bash", "-c", "echo 'Hello World'; tail -f /dev/null"]
    build:
      context: .
      dockerfile: Dockerfile.ubuntu

  fedora-server:
    image: fedora-server
    container_name: fedora-server-cont
    command: ["/bin/bash", "-c", "echo 'Hello World'; tail -f /dev/null"]
    build:
      context: .
      dockerfile: Dockerfile.fedora
