version: '3'
services:
  postgres-db:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Welcome
    volumes:
      - ./postgresql/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - common-network  # Use the common network

  phppgadmin:
    image: dpage/pgadmin4
    ports:
      - "6391:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres-db
    networks:
      - common-network  # Use the common network

networks:
  common-network:
    driver: bridge  # Use the bridge network driver (default)
