# Use the official node image with the desired version
FROM node:18.17.0-alpine

# Set the working directory in the container
WORKDIR /react

# copy package.json
COPY package.json ./

# Install the yarn package manager
RUN npm install -g yarn --force

# Install the dependencies for the react-app
RUN yarn install --force

# Expose the port (assuming your React app runs on port 3000)
EXPOSE 3000

# Start the app and library in watch mode (optional, you can override this in "docker run" command)
# CMD ["sh", "-c", "cd /react && yarn start"]
CMD ["npm", "start", "--host", "0.0.0.0", "--port", "3000", "--disableHostCheck", "true]