version: '3'
services:
    frontend:
        image: angular-webapp-dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "4200:4200"
        volumes:
            - "./:/angular"
            - "ang_node_vol:/angular/node_modules"
        profiles: ["app-dev"]
    frontend-prod:
        image: angular-webapp-prod
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports: 
            - "4300:80"
        profiles: ["app-prod"]
volumes:
  ang_node_vol: