# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy SSH

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: flask_app
      - name: Use SSH Copy to Clone Repo
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{secrets.PRIVATE_KEY}}
          port: ${{ secrets.PORT }}
          source: "flask_app"
          target: "/var/www/html"
      - name: Use SSH to Execute Scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.PRIVATE_KEY}}
          script: |
            cd /var/www/html/flask_app
            sudo apt-get update
            sudo apt-get install python3-venv
            python3 -m venv flaskenv
            source flaskenv/bin/activate
            pip install -r requirements.txt
            sudo cp -f ssh_files/flask.service /etc/systemd/system/flask.service
            sudo systemctl daemon-reload
            sudo systemctl start flask_app
            sudo systemctl enable flask_app
            sudo apt-get install nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx